DROP TABLE IF EXISTS "Table 1";
CREATE TABLE "Table 1" ("Facility Type" TEXT, "Lighting Hours" FLOAT, "HVAC Int" TEXT);
INSERT INTO "Table 1" VALUES('Auto Related',4056,'AR');
INSERT INTO "Table 1" VALUES('Bakery',2854,'FS');
INSERT INTO "Table 1" VALUES('Banks',3748,'SOfc');
INSERT INTO "Table 1" VALUES('Church',1955,'Rel');
INSERT INTO "Table 1" VALUES('College - Cafeteria ',2713,'FS');
INSERT INTO "Table 1" VALUES('College - Classes/Administrative',2586,'CC');
INSERT INTO "Table 1" VALUES('College - Dormitory',3066,'Dorm');
INSERT INTO "Table 1" VALUES('Commercial Condos',3100,'SOfc');
INSERT INTO "Table 1" VALUES('Convenience Stores',6376,'SRet');
INSERT INTO "Table 1" VALUES('Convention Center',1954,'Asy');
INSERT INTO "Table 1" VALUES('Manufacturing Facility',2857,'Ind');
INSERT INTO "Table 1" VALUES('Medical Offices',3748,'SOfc');
INSERT INTO "Table 1" VALUES('Motion Picture Theatre',1954,' Asy');
INSERT INTO "Table 1" VALUES('Multi - Family (Common Areas)',7665,'MFL');
INSERT INTO "Table 1" VALUES('Museum',3748,'Asy');
INSERT INTO "Table 1" VALUES('Nursing Homes',5840,'MFL');
INSERT INTO "Table 1" VALUES('Office (Small)',3100,'SOfc');
INSERT INTO "Table 1" VALUES('Office (Large)',3100,'LOfc');
INSERT INTO "Table 1" VALUES('Office/Retail (Small)',3748,'SOfc');
INSERT INTO "Table 1" VALUES('Office/Retail (Large)',3748,'LOfc');
INSERT INTO "Table 1" VALUES('Parking Garages',4368,'None');
INSERT INTO "Table 1" VALUES('Parking Lots',4100,'None');
INSERT INTO "Table 1" VALUES('Court House',3748,'LOfc');
INSERT INTO "Table 1" VALUES('Dining: Bar Lounge/Leisure',4182,'FS');
INSERT INTO "Table 1" VALUES('Dining: Cafeteria / Fast Food',6456,'FF');
INSERT INTO "Table 1" VALUES('Dining: Family',4182,'FS');
INSERT INTO "Table 1" VALUES('Entertainment',1952,'Asy');
INSERT INTO "Table 1" VALUES('Exercise Center',5836,'SRet');
INSERT INTO "Table 1" VALUES('Fast Food Restaurants',6376,'FF');
INSERT INTO "Table 1" VALUES('Fire Station (Unmanned)',1953,'Asy');
INSERT INTO "Table 1" VALUES('Food Stores',4055,'Gro');
INSERT INTO "Table 1" VALUES('Gymnasium',2586,'Asy');
INSERT INTO "Table 1" VALUES('Hospitals',7674,'Hosp');
INSERT INTO "Table 1" VALUES('Hospitals / Health Care',7666,'Hosp');
INSERT INTO "Table 1" VALUES('Industrial - 1 Shift',2857,'Ind');
INSERT INTO "Table 1" VALUES('Industrial - 2 Shift',4730,'Ind');
INSERT INTO "Table 1" VALUES('Industrial - 3 Shift',6631,'Ind');
INSERT INTO "Table 1" VALUES('Laundromats',4056,'SRet');
INSERT INTO "Table 1" VALUES('Library',3748,'LOfc');
INSERT INTO "Table 1" VALUES('Light Manufacturers',2613,'Ind');
INSERT INTO "Table 1" VALUES('Lodging (Hotels/Motels)',3064,'Hotel/Motel');
INSERT INTO "Table 1" VALUES('Mail Concourse',4833,'LRet');
INSERT INTO "Table 1" VALUES('Penitentiary',5477,'MFL');
INSERT INTO "Table 1" VALUES('Performing Arts Theatre',2586,'Asy');
INSERT INTO "Table 1" VALUES('Police / Fire Stations (24 Hr)',7665,'Asy');
INSERT INTO "Table 1" VALUES('Post Office',3748,'SRet');
INSERT INTO "Table 1" VALUES('Pump Stations',1949,'Ind');
INSERT INTO "Table 1" VALUES('Refrigerated Warehouse',2602,'RWH');
INSERT INTO "Table 1" VALUES('Religious Building',1955,'Rel');
INSERT INTO "Table 1" VALUES('Restaurants',4182,'FS');
INSERT INTO "Table 1" VALUES('Retail (Small)',4057,'SRet');
INSERT INTO "Table 1" VALUES('Retail (Large)',4057,'LRet');
INSERT INTO "Table 1" VALUES('School / University',2187,'Univ');
INSERT INTO "Table 1" VALUES('Schools (Jr./Sr.High)',2187,'HS');
INSERT INTO "Table 1" VALUES('Schools (Preshool/Elementary)',2187,'Sch');
INSERT INTO "Table 1" VALUES('Schools (Technical/Vocational)',2187,'CC');
INSERT INTO "Table 1" VALUES('Small Services',3750,'SOfc');
INSERT INTO "Table 1" VALUES('Sports Arena',1954,'Asy');
INSERT INTO "Table 1" VALUES('Town Hall',3748,'Asy');
INSERT INTO "Table 1" VALUES('Transportation',6456,'Asy');
INSERT INTO "Table 1" VALUES('Warehouse (Not Refrigerated)',2602,'WH');
INSERT INTO "Table 1" VALUES('Waste Water Treatment Plant',6631,'Ind');
INSERT INTO "Table 1" VALUES('Workshop',3750,'Ind');
